version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c '
      npm install &&
      npm start
      '
    ports:
      - "3000:3000"
    networks:
      - all

networks:
  all:
